# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ls_equip.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ls_equip(object):
    def setupUi(self, ls_equip):
        ls_equip.setObjectName("ls_equip")
        ls_equip.resize(404, 600)
        self.centralwidget = QtWidgets.QWidget(ls_equip)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.Delete = QtWidgets.QPushButton(self.widget)
        self.Delete.setObjectName("Delete")
        self.horizontalLayout.addWidget(self.Delete)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        ls_equip.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ls_equip)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 21))
        self.menubar.setObjectName("menubar")
        ls_equip.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ls_equip)
        self.statusbar.setObjectName("statusbar")
        ls_equip.setStatusBar(self.statusbar)

        self.retranslateUi(ls_equip)
        QtCore.QMetaObject.connectSlotsByName(ls_equip)

    def retranslateUi(self, ls_equip):
        _translate = QtCore.QCoreApplication.translate
        ls_equip.setWindowTitle(_translate("ls_equip", "MainWindow"))
        self.pushButton.setText(_translate("ls_equip", "Add"))
        self.Delete.setText(_translate("ls_equip", "Delete"))
